apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-cloud
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
    spec:
      serviceAccountName: echo-cloud-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: gcr.io/PROJECT_ID/echo-cloud:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: GOOGLE_CLOUD_PROJECT
              value: "PROJECT_ID"
            - name: CODESSA_API_URL
              value: "https://api.codessa.ai"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: gcp-secrets
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: gcp-secrets
          secret:
            secretName: codessa-deploy-key
  traffic:
    - percent: 100
      latestRevision: true
