apiVersion: batch/v1
kind: Job
metadata:
  name: echo-terminal-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: echo-terminal
          image: ghcr.io/echoforge/echo-terminal:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
          command: ['node', 'dist/index.js']
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
