apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoforge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/echoforge.git
    targetRevision: main
    path: charts/echoforge
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: echoforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
