global:
  registry: ghcr.io/echoforge
  tag: latest

monitoring:
  enabled: true
  interval: 30s
  dashboardEnabled: true

echoCloud:
  replicaCount: 2
  env:
    NODE_ENV: production
    PORT: '3000'

dashboard:
  replicaCount: 2
  env:
    NODE_ENV: production
    PORT: '3000'
    NEXT_PUBLIC_API_BASE: http://echo-cloud

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: false
    secretName: echoforge-tls
  hosts:
    dashboard: dashboard.staging.local
    api: api.staging.local
  canary:
    enabled: true
    header: 'X-Canary'
