{{- if and .Values.ingress.enabled .Values.ingress.canary.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoforge-canary
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/canary: "true"
    {{- if .Values.ingress.canary.header }}
    nginx.ingress.kubernetes.io/canary-by-header: {{ .Values.ingress.canary.header | quote }}
    {{- else }}
    nginx.ingress.kubernetes.io/canary-weight: {{ .Values.ingress.canary.weight | quote }}
    {{- end }}
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts.dashboard | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.api | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-cloud
                port:
                  number: 80
{{- end }}
