{{- if and .Values.monitoring.enabled .Values.monitoring.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: echoforge-alerts
  labels:
    release: prometheus
spec:
  groups:
    - name: echoforge.rules
      rules:
        - alert: EchoCloudHighErrorRate
          expr: |
            sum(rate(http_requests_total{status=~"5.."}[5m]))
              / sum(rate(http_requests_total[5m])) > {{ .Values.monitoring.alerts.errorRateThreshold | default 0.05 }}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High 5xx error rate on echo-cloud"
            description: ">
              5xx error rate is above threshold for the last 5m."
        - alert: EchoCloudHighLatencyP95
          expr: |
            histogram_quantile(0.95,
              sum by (le) (rate(http_request_duration_seconds_bucket[5m]))
            ) > {{ .Values.monitoring.alerts.p95LatencySeconds | default 0.5 }}
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High p95 latency on echo-cloud"
            description: ">
              p95 request latency is above threshold for the last 10m."
{{- end }}
