{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: echoforge-servicemonitor
  labels:
    release: prometheus
    {{- range $k, $v := .Values.monitoring.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval | default "30s" }}
  selector:
    matchLabels:
      app: echo-cloud
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
